import {useEffect,useMemo,useState} from 'react';
import {ArrowUp,BracketsCurly,Check,CaretRight,Command,GameController,GitDiff,Lightning,MagnifyingGlass,Plus,SidebarSimple,Sparkle,TreeStructure,WifiHigh,Wrench,X} from 'phosphor-react';
import {initialMessages,sessions,tree} from './data';
import type {ChatMessage,InstanceNode} from './types';

const IconButton=({label,children,onClick}:{label:string;children:React.ReactNode;onClick?:()=>void})=><button className="icon-button" aria-label={label} title={label} onClick={onClick}>{children}</button>;

function ExplorerNode({node,depth=0}:{node:InstanceNode;depth?:number}){const [open,setOpen]=useState(depth<1);return <div><button className="tree-row" style={{paddingLeft:`${12+depth*17}px`}} onClick={()=>setOpen(v=>!v)}>{node.children?<CaretRight className={open?'open':''} size={13}/>:<span className="tree-spacer"/>}<span className={`instance-dot ${node.type.toLowerCase()}`}/><span>{node.name}</span><small>{node.type}</small></button>{open&&node.children?.map(child=><ExplorerNode key={child.id} node={child} depth={depth+1}/>)}</div>}

function CommandMenu({close}:{close:()=>void}){return <div className="scrim" onMouseDown={close}><section className="command-menu" onMouseDown={e=>e.stopPropagation()}><div className="command-search"><MagnifyingGlass size={18}/><input autoFocus placeholder="Type a command or search…"/><kbd>esc</kbd></div><p className="menu-label">Quick actions</p>{[['Connect to Studio','Detect an open Roblox Studio session'],['Run playtest','Test the current experience'],['Review changes','Inspect the latest generated edits'],['New workspace','Start a focused build session']].map(([a,b],i)=><button className="command-item" key={a}><span>{[<WifiHigh/>,<GameController/>,<GitDiff/>,<Plus/>][i]}</span><div><b>{a}</b><small>{b}</small></div><kbd>⌘{i+1}</kbd></button>)}</section></div>}

export function App(){
 const [sidebar,setSidebar]=useState(true),[panel,setPanel]=useState<'explorer'|'changes'|'playtest'>('explorer'),[command,setCommand]=useState(false),[connected,setConnected]=useState(false),[messages,setMessages]=useState(initialMessages),[prompt,setPrompt]=useState('');
 const [building,setBuilding]=useState(false);const wordCount=useMemo(()=>prompt.trim()?prompt.trim().split(/\s+/).length:0,[prompt]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommand(true)}if(e.key==='Escape')setCommand(false)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 const send=()=>{if(!prompt.trim()||building)return;const content=prompt.trim();setPrompt('');setMessages(v=>[...v,{id:crypto.randomUUID(),role:'user',content}]);setBuilding(true);setTimeout(()=>{setMessages(v=>[...v,{id:crypto.randomUUID(),role:'assistant',content:'I mapped the request into a safe build plan. Connect Roblox Studio to apply these changes to your place.',steps:['Scanned the requested systems and dependencies','Prepared an isolated implementation plan','Queued a playtest and rollback checkpoint']}]);setBuilding(false)},900)};
 return <div className={`app ${sidebar?'':'sidebar-closed'}`}>
  <a className="skip" href="#composer">Skip to composer</a>
  <header className="topbar"><div className="brand"><IconButton label="Toggle sidebar" onClick={()=>setSidebar(v=>!v)}><SidebarSimple size={19}/></IconButton><span className="brand-mark">S</span><b>Stud Blox</b><span className="beta">PREVIEW</span></div><button className="command-trigger" onClick={()=>setCommand(true)}><MagnifyingGlass size={15}/>Search or run a command <kbd>⌘ K</kbd></button><div className="top-actions"><button className={`connection ${connected?'connected':''}`} onClick={()=>setConnected(v=>!v)}><span/><WifiHigh size={16}/>{connected?'Studio connected':'Connect Studio'}</button><div className="avatar">RD</div></div></header>
  {sidebar&&<aside className="sidebar"><button className="new-chat"><Plus size={17}/>New build session <kbd>⌘ N</kbd></button><div className="side-section"><p>Workspace</p><button className="side-link active"><Sparkle/>Agent</button><button className="side-link"><BracketsCurly/>Scripts</button><button className="side-link"><Wrench/>Skills <span>6</span></button></div><div className="session-heading"><p>Recent sessions</p><button>View all</button></div><div className="sessions">{sessions.map(s=><button className={`session ${s.status==='active'?'active':''}`} key={s.id}><span>{s.title}</span><small>{s.updated}</small></button>)}</div><div className="sidebar-foot"><div className="usage"><span><Lightning/>This week</span><b>63%</b><i><i/></i></div><button className="side-link"><Command/>Keyboard shortcuts</button></div></aside>}
  <main className="workspace"><section className="chat"><div className="chat-header"><div><p>BUILD SESSION</p><h1>Combat arena prototype</h1></div><button className="model"><span/>Claude Sonnet 4.6 <CaretRight size={13}/></button></div><div className="messages">{messages.map(m=><article className={`message ${m.role}`} key={m.id}>{m.role==='assistant'&&<div className="agent-icon"><Sparkle size={15}/></div>}<div className="bubble"><p>{m.content}</p>{m.steps&&<div className="steps">{m.steps.map(x=><div key={x}><Check size={13}/><span>{x}</span></div>)}</div>}{m.role==='assistant'&&<div className="message-actions"><button>Copy</button><button>Open changes</button></div>}</div></article>)}{building&&<article className="message assistant"><div className="agent-icon"><Sparkle size={15}/></div><div className="thinking"><i/><i/><i/><span>Planning the build</span></div></article>}</div><div className="composer-wrap"><div className="composer" id="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Describe what you want to build or change…" aria-label="Build prompt"/><div className="composer-tools"><div><button title="Add context"><Plus size={17}/></button><button className="mode"><Sparkle size={14}/>Agent</button><button className="mode">Balanced <CaretRight size={12}/></button></div><span>{wordCount>0&&`${wordCount} words`}<button className="send" disabled={!prompt.trim()} onClick={send} aria-label="Send"><ArrowUp size={17}/></button></span></div></div><p className="hint">Stud Blox can make mistakes. Review scripts and playtest before publishing.</p></div></section>
  <aside className="inspector"><div className="tabs"><button className={panel==='explorer'?'active':''} onClick={()=>setPanel('explorer')}><TreeStructure/>Explorer</button><button className={panel==='changes'?'active':''} onClick={()=>setPanel('changes')}><GitDiff/>Changes <span>7</span></button><button className={panel==='playtest'?'active':''} onClick={()=>setPanel('playtest')}><GameController/>Test</button></div>{panel==='explorer'&&<><div className="panel-search"><MagnifyingGlass/><input placeholder="Filter instances"/></div><div className="tree">{tree.map(n=><ExplorerNode key={n.id} node={n}/>)}</div><div className="properties"><p>SELECTION</p><div className="empty-selection"><TreeStructure size={25}/><span>Select an instance to inspect its properties</span></div></div></>}{panel==='changes'&&<div className="change-list"><div className="change-summary"><b>7 changes ready</b><span>+184 −23</span></div>{['RoundService.server.lua','SafeZoneController.lua','ArenaConfig.lua','RoundState'].map((x,i)=><button key={x}><span className={i===3?'added':'modified'}>{i===3?'A':'M'}</span><div>{x}<small>{i===3?'ReplicatedStorage':'ServerScriptService'}</small></div><CaretRight/></button>)}</div>}{panel==='playtest'&&<div className="playtest"><div className="test-orbit"><GameController size={31}/></div><h3>Ready to test</h3><p>Run the experience and watch server output, assertions, and player flows here.</p><button>Start playtest</button><small>Studio must be connected</small></div>}</aside>
  </main>{command&&<CommandMenu close={()=>setCommand(false)}/>}</div>
}
