import {useState} from 'react';
import {ArrowRight,BracketsCurly,Check,Cube,DownloadSimple,GameController,HardDrives,Sparkle} from 'phosphor-react';
import {Landing} from './Landing';

// Reuse the mature account modal from Landing through its header entry points while
// presenting a desktop-only public product surface.
export function DesktopLanding(){
 const [accountSite,setAccountSite]=useState(false);
 if(accountSite)return <Landing openApp={()=>setAccountSite(false)}/>;
 const releases='https://github.com/Radin-dev1/Studblox/releases';
 return <div className="landing desktop-landing">
  <header className="landing-nav"><a className="landing-brand" href="#top"><span>S</span>Stud Blox</a><nav><a href="#features">Features</a><a href="#workflow">Workflow</a><a href="#models">Models</a><a href={releases}>Downloads</a></nav><div><button className="nav-login" onClick={()=>setAccountSite(true)}>Log in</button><button className="nav-signup" onClick={()=>setAccountSite(true)}>Sign up</button></div></header>
  <main id="top">
   <section className="hero"><div className="hero-copy"><p><span/>OPEN-SOURCE ROBLOX DESKTOP AGENT</p><h1>Build games.<br/>Stay in control.</h1><div className="hero-body">Stud Blox is a desktop application that connects your chosen AI model directly to Roblox Studio. Script classes, build systems, find assets, generate art, and inspect every change.</div><div className="hero-actions"><button onClick={()=>window.location.assign(releases)}><DownloadSimple/>View desktop releases</button><button onClick={()=>setAccountSite(true)}>Create account</button></div><small>Desktop only · Windows first · Local models supported · Open source</small></div><div className="hero-window"><div className="window-bar"><i/><i/><i/><span>Stud Blox Desktop — Arena project</span></div><div className="window-body"><aside><b>EXPLORER</b>{['Workspace','Players','Lighting','ReplicatedStorage','ServerScriptService','StarterGui'].map((x,i)=><div key={x} className={i===4?'selected':''}><span>{['◉','♟','◐','▣','◆','▱'][i]}</span>{x}</div>)}</aside><article><header><BracketsCurly/>RoundService.lua <span>AI reviewed</span></header><pre><em>01</em> local Players = game:GetService(<b>"Players"</b>){'\n'}<em>02</em>{'\n'}<em>03</em> local RoundService = {'{}'}{'\n'}<em>04</em> RoundService.__index = RoundService{'\n'}<em>05</em>{'\n'}<em>06</em> function RoundService:startRound(){'\n'}<em>07</em>   self.players = Players:GetPlayers(){'\n'}<em>08</em> end</pre><div className="window-prompt"><Sparkle/><span>Make rounds wait until two players join</span><ArrowRight/></div></article></div></div></section>
   <section className="proof"><span>DESKTOP WORKSPACE FOR</span>{['SCRIPTING','GAME SYSTEMS','CREATOR STORE','3D + 2D ASSETS','PLAYTESTING'].map(x=><b key={x}>{x}</b>)}</section>
   <section className="product" id="features"><div className="section-intro"><p>BUILT FOR ROBLOX STUDIO</p><h2>One desktop workspace.<br/>Every part of the game.</h2><span>Stud Blox reads the project hierarchy and selected classes through Studio’s MCP connection. Proposed work stays visible before it is applied.</span></div><div className="feature-grid"><article className="feature-large"><BracketsCurly/><span>01 / SCRIPT</span><h3>Click a class. Ask AI to script it.</h3><p>Select an instance in the Explorer and give the agent a goal. It sees the correct class, properties, related scripts, and existing architecture.</p><div className="mini-tree">{['Workspace','ReplicatedStorage','ServerScriptService','  RoundService.lua'].map((x,i)=><div className={i===3?'active':''} key={x}>{x}<span>{i===3?'ModuleScript':'Class'}</span></div>)}</div></article><article><GameController/><span>02 / BUILD</span><h3>Plan complete games</h3><p>Split a concept into map, UI, systems, persistence, and playtest workstreams.</p></article><article><Cube/><span>03 / ASSETS</span><h3>Find or generate assets</h3><p>Inspect Creator Store results or draft original 3D models, textures, icons, and interface art.</p></article></div></section>
   <section className="workflow" id="workflow"><div><p>QUALITY, BUILT IN</p><h2>It does not stop<br/>at the first answer.</h2></div><ol>{[['01','Inspect','Read the place, scripts, dependencies, and selected classes.'],['02','Plan','Break the request into reversible changes.'],['03','Build','Write modular, server-authoritative Luau.'],['04','Review','Check security, performance, and every diff.'],['05','Test + repair','Playtest and fix failures before completion.']].map(([n,t,d])=><li key={n}><b>{n}</b><span><strong>{t}</strong>{d}</span><Check/></li>)}</ol></section>
   <section className="models" id="models"><div><p>YOUR MODEL. YOUR COMPUTER.</p><h2>Local first.<br/>APIs when needed.</h2><span>Run an open model on your machine with Ollama or LM Studio. Cloud APIs remain optional.</span></div><div className="model-stack"><article><HardDrives/><b>Ollama</b><span>Default · Local · Free</span></article><article><HardDrives/><b>LM Studio</b><span>Local · Private</span></article><article><Sparkle/><b>Cloud APIs</b><span>OpenAI · Anthropic · OpenRouter</span></article></div></section>
   <section className="final-cta"><DownloadSimple/><p>DESKTOP APPLICATION</p><h2>Build beside Studio.<br/>Not inside a browser.</h2><button onClick={()=>window.location.assign(releases)}><DownloadSimple/>View desktop releases</button><button className="text-cta" onClick={()=>setAccountSite(true)}>or manage your account</button></section>
  </main><footer><a className="landing-brand" href="#top"><span>S</span>Stud Blox</a><p>Desktop AI tooling for Roblox creators.</p><div><a href="https://github.com/Radin-dev1/Studblox">GitHub</a><a href={releases}>Releases</a></div></footer>
 </div>
}
