import {FormEvent,useState} from 'react';
import {ArrowRight,BracketsCurly,Check,Cube,GameController,GitDiff,HardDrives,ShieldCheck,Sparkle,X} from 'phosphor-react';
import {authConfigured,signInWithProvider,supabase} from './lib/supabase';

function AuthPanel({mode,close,switchMode,onSuccess}:{mode:'login'|'signup';close:()=>void;switchMode:(m:'login'|'signup')=>void;onSuccess:()=>void}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(mode==='signup'&&name.trim().length<2){setError('Enter your name.');return}if(!/^\S+@\S+\.\S+$/.test(email)){setError('Enter a valid email address.');return}if(password.length<8){setError('Password must contain at least 8 characters.');return}if(!supabase){setError('Supabase is not configured on this deployment.');return}setBusy(true);setError('');const result=mode==='signup'?await supabase.auth.signUp({email,password,options:{data:{display_name:name.trim()},emailRedirectTo:window.location.origin+window.location.pathname}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error){setError(result.error.message);return}if(mode==='signup'&&!result.data.session){setError('Check your email to confirm your account, then log in.');return}onSuccess()};
 const social=async(provider:'google'|'github'|'discord')=>{try{setBusy(true);setError('');await signInWithProvider(provider)}catch(e){setBusy(false);setError(e instanceof Error?e.message:'Could not start social sign-in.')}};
 return <div className="auth-scrim" onMouseDown={close}><section className="auth-panel" onMouseDown={e=>e.stopPropagation()}><button className="auth-close" onClick={close} aria-label="Close"><X/></button><span className="auth-mark">S</span><p>{mode==='signup'?'CREATE YOUR ACCOUNT':'WELCOME BACK'}</p><h2>{mode==='signup'?'Start building with Stud Blox.':'Log in to your workspace.'}</h2><div className="social-auth"><button disabled={busy} onClick={()=>social('google')}><b>G</b>Continue with Google</button><button disabled={busy} onClick={()=>social('github')}><b>GH</b>Continue with GitHub</button><button disabled={busy} onClick={()=>social('discord')}><b>D</b>Continue with Discord</button></div><div className="auth-divider"><span>or use email</span></div><form onSubmit={submit}>{mode==='signup'&&<label>Name<input autoFocus value={name} onChange={e=>setName(e.target.value)} autoComplete="name" placeholder="Your name"/></label>}<label>Email<input autoFocus={mode==='login'} value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="you@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='signup'?'new-password':'current-password'} placeholder="At least 8 characters"/></label>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?'Connecting…':mode==='signup'?'Create account':'Log in'}<ArrowRight/></button></form><div className="auth-switch">{mode==='signup'?'Already have an account?':'New to Stud Blox?'} <button onClick={()=>switchMode(mode==='signup'?'login':'signup')}>{mode==='signup'?'Log in':'Create an account'}</button></div><small>{authConfigured?'Authentication is secured by Supabase.':'Add the Supabase GitHub variables to enable authentication.'}</small></section></div>
}

export function Landing({openApp}:{openApp:()=>void}){
 const [auth,setAuth]=useState<'login'|'signup'|null>(null);
 const success=()=>{setAuth(null);openApp()};
 return <div className="landing">
  <header className="landing-nav"><a className="landing-brand" href="#top"><span>S</span>Stud Blox</a><nav><a href="#product">Product</a><a href="#workflow">Workflow</a><a href="#models">Models</a><a href="https://github.com/Radin-dev1/Studblox" target="_blank" rel="noreferrer">GitHub</a></nav><div><button className="nav-login" onClick={()=>setAuth('login')}>Log in</button><button className="nav-signup" onClick={()=>setAuth('signup')}>Sign up</button></div></header>
  <main id="top"><section className="hero"><div className="hero-copy"><p><span/>OPEN-SOURCE ROBLOX BUILD AGENT</p><h1>From an idea<br/>to a working game.</h1><div className="hero-body">Stud Blox connects AI models to Roblox Studio. Build systems, write Luau, find assets, generate art, and inspect every change before it reaches your place.</div><div className="hero-actions"><button onClick={()=>setAuth('signup')}>Start building free<ArrowRight/></button><button onClick={openApp}>Open workspace</button></div><small>No credit card · Local models supported · Open source</small></div><div className="hero-window"><div className="window-bar"><i/><i/><i/><span>Stud Blox — Arena project</span></div><div className="window-body"><aside><b>EXPLORER</b>{['Workspace','Players','Lighting','ReplicatedStorage','ServerScriptService','StarterGui'].map((x,i)=><div key={x} className={i===4?'selected':''}><span>{['◉','♟','◐','▣','◆','▱'][i]}</span>{x}</div>)}</aside><article><header><BracketsCurly/>RoundService.lua <span>AI reviewed</span></header><pre><em>01</em> local Players = game:GetService(<b>"Players"</b>){'\n'}<em>02</em>{'\n'}<em>03</em> local RoundService = {'{}'}{'\n'}<em>04</em> RoundService.__index = RoundService{'\n'}<em>05</em>{'\n'}<em>06</em> function RoundService:startRound(){'\n'}<em>07</em>   self.players = Players:GetPlayers(){'\n'}<em>08</em> end</pre><div className="window-prompt"><Sparkle/><span>Make rounds wait until two players join</span><ArrowRight/></div></article></div></div></section>
  <section className="proof"><span>ONE WORKSPACE FOR</span>{['SCRIPTING','GAME SYSTEMS','CREATOR STORE','3D + 2D ASSETS','PLAYTESTING'].map(x=><b key={x}>{x}</b>)}</section>
  <section className="product" id="product"><div className="section-intro"><p>THE PRODUCT</p><h2>AI that works inside the project,<br/>not beside it.</h2><span>Stud Blox understands the hierarchy, selected classes, scripts, and current task. You stay in control of what changes.</span></div><div className="feature-grid"><article className="feature-large"><BracketsCurly/><span>01 / SCRIPT</span><h3>Select anything. Ask AI to script it.</h3><p>Click a service, instance, or class in the Explorer. Stud Blox passes the right context to the model and opens every proposed edit as a diff.</p><div className="mini-tree">{['Workspace','ReplicatedStorage','ServerScriptService','  RoundService.lua'].map((x,i)=><div className={i===3?'active':''} key={x}>{x}<span>{i===3?'ModuleScript':'Class'}</span></div>)}</div></article><article><GameController/><span>02 / BUILD</span><h3>Plan complete games</h3><p>Turn one description into map, UI, systems, data, and playtest workstreams.</p></article><article><Cube/><span>03 / ASSETS</span><h3>Find or generate assets</h3><p>Search the Creator Store or draft original 3D models, textures, icons, and interface art.</p></article></div></section>
  <section className="workflow" id="workflow"><div><p>QUALITY, BUILT IN</p><h2>It does not stop<br/>at the first answer.</h2></div><ol>{[['01','Inspect','Read the place, scripts, dependencies, and selected classes.'],['02','Plan','Break the request into reversible, reviewable changes.'],['03','Build','Write modular, server-authoritative Luau and scene changes.'],['04','Review','Check security, performance, regressions, and every diff.'],['05','Test + repair','Run focused playtests and fix failures before completion.']].map(([n,t,d])=><li key={n}><b>{n}</b><span><strong>{t}</strong>{d}</span><Check/></li>)}</ol></section>
  <section className="models" id="models"><div><p>YOUR MODEL. YOUR CHOICE.</p><h2>Local first.<br/>APIs when you want them.</h2><span>Start free with an open model running on your computer. Connect a cloud model only when a project needs it.</span></div><div className="model-stack"><article><HardDrives/><b>Ollama</b><span>Default · Local · Free</span></article><article><HardDrives/><b>LM Studio</b><span>Local · Private</span></article><article><Sparkle/><b>Cloud APIs</b><span>OpenAI · Anthropic · OpenRouter</span></article></div></section>
  <section className="final-cta"><ShieldCheck/><p>BUILD WITH CONTROL</p><h2>Your game. Your model.<br/>Every change visible.</h2><button onClick={()=>setAuth('signup')}>Create your account<ArrowRight/></button><button className="text-cta" onClick={openApp}>or open the workspace</button></section></main>
  <footer><a className="landing-brand" href="#top"><span>S</span>Stud Blox</a><p>Open-source AI tooling for Roblox creators.</p><div><a href="https://github.com/Radin-dev1/Studblox">GitHub</a><a href="#">Privacy</a><a href="#">Terms</a></div></footer>
  {auth&&<AuthPanel mode={auth} close={()=>setAuth(null)} switchMode={setAuth} onSuccess={success}/>}
 </div>
}
